no_cuda: False
checkpoint: "results/dorefa_resnet_cifar10" 
filename: null
pretrained: null

bin_type: 'dorefa'

model : "dorefa_resnet18"
save_path: "results/dorefa_resnet_cifar10" 
dataset : "cifar10"
batch_size: 128 
test_batch_size: 100
optimizer: 'sgd' 
lr: 0.01 
gamma: 0.1 
steps: [80, 150] 
epochs: 300 

