no_cuda: False
checkpoint: "results/nin_cifar10" 
filename: null
pretrained: null

model : "nin"
save_path: "results/nin_cifar10" 
dataset : "cifar10"
batch_size: 128 
test_batch_size: 100
optimizer: 'adam' 
lr: 0.01 
gamma: 0.1 
steps: [80, 150] 
epochs: 300 

